version: '3'
services:
  db:
    image: mysql:5.7.22
    build: docker/db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  backend:
    build: docker/backend
  frontend:
    build: docker/frontend
    ports:
      - 80:8080
      - 8443:8443
    depends_on:
      - db
      - backend
