name: CaptainHook

on: [repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Starting the deployment
      env: # Or as an environment variable
        EC2: ${{ secrets.EC2 }}
        TRAVIS_CI_SECRET: ${{ secrets.TRAVIS_CI_SECRET }}
      run: |
        export BRANCH=$(echo ${{ github.event.action }} | cut -f1 -d':')
        export COMMIT=$(echo ${{ github.event.action }} | cut -f2 -d':')
        openssl aes-256-cbc -pass "pass:$TRAVIS_CI_SECRET" -in ./deploy/.secret -out ./try.arrow-kt.pem -d -a -nopad
        chmod 400 ./try.arrow-kt.pem
        ssh -o "StrictHostKeyChecking no" -q -i ./try.arrow-kt.pem $EC2 'cd try.arrow-kt.io; sh deploy.sh $BRANCH $COMMIT; exit'
